name: fave_places
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  image_picker: ^1.1.2
  location: ^8.0.0
  http: ^1.3.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/images/user.jpg"
    - .env
