name: shop_app
description: "A shopping list application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pencil.svg
    - assets/images/logout.svg

  fonts:
    - family: SourGummy
      fonts:
        - asset: assets/fonts/SourGummy.ttf
        - asset: assets/fonts/SourGummy-Italic.ttf
          style: italic
